var ScrabbleTiles = {
  "A": {"value": 1, "original": 9, "remaining": 9},
  "B": {"value": 3, "original": 2, "remaining": 2},
  "C": {"value": 3, "original": 2, "remaining": 2},
  "D": {"value": 2, "original": 4, "remaining": 4},
  "E": {"value": 1, "original": 12, "remaining": 12},
  "F": {"value": 4, "original": 2, "remaining": 2},
  "G": {"value": 2, "original": 3, "remaining": 3},
  "H": {"value": 4, "original": 2, "remaining": 2},
  "I": {"value": 1, "original": 9, "remaining": 9},
  "J": {"value": 8, "original": 1, "remaining": 1},
  "K": {"value": 5, "original": 1, "remaining": 1},
  "L": {"value": 1, "original": 4, "remaining": 4},
  "M": {"value": 3, "original": 2, "remaining": 2},
  "N": {"value": 1, "original": 6, "remaining": 6},
  "O": {"value": 1, "original": 8, "remaining": 8},
  "P": {"value": 3, "original": 2, "remaining": 2},
  "Q": {"value": 10, "original": 1, "remaining": 1},
  "R": {"value": 1, "original": 6, "remaining": 6},
  "S": {"value": 1, "original": 4, "remaining": 4},
  "T": {"value": 1, "original": 6, "remaining": 6},
  "U": {"value": 1, "original": 4, "remaining": 4},
  "V": {"value": 4, "original": 2, "remaining": 2},
  "W": {"value": 4, "original": 2, "remaining": 2},
  "X": {"value": 8, "original": 1, "remaining": 1},
  "Y": {"value": 4, "original": 2, "remaining": 2},
  "Z": {"value": 10, "original": 1, "remaining": 1}
};
